### ISSUE TITLE
[Feat] SmartStart support + Wider support for frameworks

### ISSUE THREAD

**Issue by georgeinva2004** [zwave-js/ZWaveJS.NET#14]
Diving into this package and I have to say you all are doing wonderful work!!!!

Any timeline on the SmartStart support?

**Comment by marcus-j-davies** [comment]
Hi @georgeinva2004,

Thanks for the kind words - @AlCalzone  and the team are certainly grateful.

I have a task to complete some updates on this package, I haven't touched it in a while (other project involvements).
with that said - I have a Branch I am working on, and will aim to get Smart Start supported, before its release.
As for timescales - I can't commit anything at this time - Sorry, but rest assured its on my radar.

**Comment by georgeinva2004** [comment]
One more ask :)  Would you consider multi-targeting this to .net Standard 2.0 to allow it to be used with other .NET frameworks?

**Comment by marcus-j-davies** [comment]
Sure,

My 3.0 release will hopefully see a variance on the supported frameworks.

**Comment by marcus-j-davies** [comment]
@georgeinva2004 

An update for you, progress is being made to retarget this project to more frameworks.
I will be targeting `NET45` and `netstandard2.0`

This should give good coverage, I can't go below 4.5, as I use some of its API's
(and of course they exist in  `netstandard2.0`)

Watch this space 👍 

![image](https://user-images.githubusercontent.com/55892693/166982727-22f7dba9-b6a3-40af-9c79-1970c381a1ac.png)

**Comment by georgeinva2004** [comment]
This is fantastic!!!  Thanks for making these changes...

**Comment by georgeinva2004** [comment]
I took a peek at the V3 build.  Things are looking great.  Haven't tried the SmartStart functionality yet, but it looks like you've made lots of progress.   Hopefully, you find this helpful, but I took the liberty of adding support for ZWaveMulticastGroups to the V2 branch.  I'm attaching the changed files to this message.  It was very straight forward to do thanks to your very clean architecture
[MulticastGroupFiles.zip](https://github.com/zwave-js/ZWaveJS.NET/files/8835214/MulticastGroupFiles.zip)
.

**Comment by marcus-j-davies** [comment]
Hi @georgeinva2004 

I am due to release V3 (and the Toolkit demo) in the next few days (Evan soon maybe) 😃 
I will look at the source you supplied now and will transpose it to V3 👍

**Comment by marcus-j-davies** [comment]
@georgeinva2004 

I have used your work to include Multicast Support - but its tied to the controller.
When using ZWave JS in its native form - you obtain the Multicast group from the controller.

https://zwave-js.github.io/node-zwave-js/#/api/controller?id=getmulticastgroup

So we will follow that (below) - My aim is to stick as close as possible to the ZWave JS API - meaning documentation it provides, can be used for .NET

```c#
VirtualNode VN = _Driver.Controller.GetMulticastGroup(new int[] { 2,3,4,6,7});
VN.GetDefinedValueIDs();
VN.GetEndpointCount();
VN.SetValue();
VN.SupportsCCAPI();
VN.InvokeCCAPI();
```

Thanks for the contribution - and watch this space for a release 😅

**Comment by georgeinva2004** [comment]
Good point.  Thanks for fixing it...

**Comment by marcus-j-davies** [comment]
@georgeinva2004 

https://github.com/zwave-js/ZWaveJS.NET/tree/v3.0#network-toolkit-demo-application

I will be releasing V3 this evening 😬

**Comment by marcus-j-davies** [comment]
V3.0.0 is now available via nuget 

https://github.com/zwave-js/ZWaveJS.NET/releases

Toolkit demo is attached to the release on GitHub.
