### ISSUE TITLE
Logging config not settable

### ISSUE THREAD

**Issue by georgeinva2004** [zwave-js/ZWaveJS.NET#16]
Implemented V3 and it looks great!!!!  I needed to rework my app to handle mapping of CMDResults to models my app required, but otherwise, working great!  Thank-you and well-done!!!!!!

I did notice that the Options.logConfig property is readonly (with a private setter only), so it's not possible to adjust the logging behavior.  Not sure if you intended that to be for your own use or generally available.  Either way, I thought I would point it out.

Thanks again for your great work!

**Comment by marcus-j-davies** [comment]
Hi @georgeinva2004,
The instance can't be set - but the instance properties within can be.
i.e `Options.logConfig.filename = "./zwave.log"`

```c#
 public class CFGLogConfig
    {
        public bool logToFile { get; set; }
        public bool enabled { get; set; }
        public Enums.LogLevel level { get; set; }
        public int[] nodeFilter { get; set; }
        public string filename { get; set; }
    }
```

**Comment by marcus-j-davies** [comment]
> mapping of CMDResults 

Yeah - prior to V3, I was not taking into consideration any error, that may be returned, so was assuming the expected result will always be returned - which of course is not always the case 😅.

providing **Success** is true the Payload (if any) should be provided, if **Success** is false - it will hold any error message retuned by the driver.

**Comment by marcus-j-davies** [comment]
Feel free to open up a conversation - Have just enabled them on the repo 👍 
assuming this is safe to close.
