### ISSUE TITLE
Access to homeID

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#33]
When a client connects  to the ZWave JS server, the first message it receives includes the homeID that identify the ZWave network.
https://github.com/zwave-js/zwave-js-server#api

Could we add access to this value in version 4?
Or is there any other way to get this value using the ZWaveJS.NET lib?

Thanks

**Comment by marcus-j-davies** [comment]
Hi @spudwebb,

This should already be available as `Driver.Controller.homeId`?

If it's not - sure, it's trivial to add.

**Comment by spudwebb** [comment]
Ooops I missed that property, sorry.
It works thanks!
