### ISSUE TITLE
ccSpecific in ValueMetadata

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#34]
Is there a way to get the ValueMetadata.ccSpecific field?
https://zwave-js.github.io/node-zwave-js/#/api/valueid?id=valuemetadata

If not, could this be added to the ValueMetadata class in 4.0.0 ?
Thanks

**Comment by marcus-j-davies** [comment]
Hi @spudwebb,

Done! 🤓 
Here https://github.com/zwave-js/ZWaveJS.NET/pull/31/commits/8ce2e866900d4285370c03272fb52262e9c8ae2e

**Comment by marcus-j-davies** [comment]
Monitor the PR here: https://github.com/zwave-js/ZWaveJS.NET/pull/31
