### ISSUE TITLE
No error or exception when websocket client fails to connect in client mode

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#36]
I'm using the ZWaveJS.NET library in client mode, i.e I use some code similar to the example below to connect to an already running ZWave JS server.
If the ZWaveJS Server is not running, I would expect the StartUpError event to be raised but it isn't, and no exception is thrown either. Is there a way to detect that connection has failed?

I'm testing with the 4.0.0 branch, but I think there is the same problem with the main branch.

   ```csharp
 internal class Program
    {
        static Driver _driver;
        static int schemaVersion = 17;
        static string zWaveJSServerUrl = "ws://localhost:3000";

        static void Main(string[] args)
        {
            try
            {
                _driver = new Driver(new Uri(zWaveJSServerUrl), schemaVersion);
                _driver.DriverReady += Driver_DriverReady;
                _driver.StartUpError += Driver_StartupErrorEvent;
                _driver.Start();

                Console.WriteLine("press enter to stop");
                Console.ReadKey();
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }

        static private void Driver_StartupErrorEvent(string message)
        {
            Console.WriteLine(message);
        }

        static private void Driver_DriverReady()
        {
            Console.WriteLine("Driver ready");
        }
}
```

**Comment by marcus-j-davies** [comment]
Hi @spudwebb 

The connection error reporting isn't that great currently, it's one of the reasons I have moved to a different socket library in v4 - to open up better handling.

This area is still being improved/ developed in v4, so the connection error handling is still a work in progress.

I'm looking to add a timeout constant on the driver class, that is used in client mode only, and if no connection after that time is confirmed, it will then throw.

I haven't tested much (at all) using the code in client mode - but in reality, when v4 has this area nailed - it should also work in client mode.

I'll keep this issue open until I have sorted this area out. 👍

**Comment by marcus-j-davies** [comment]
You could check Driver.ZWaveJSServerVersion is populated - as that is take from the connected server, and after say a few seconds it's not populated - you could assume lots not connected?

**Comment by marcus-j-davies** [comment]
@spudwebb

Do you want to pull the latest codebase for V4?
I have just added a commit (https://github.com/zwave-js/ZWaveJS.NET/commit/46ed17201ebd64a2f6f9850fd41bdd5399132c7b), that should now handle issues connecting to a server (weather or not it's hosting its own)

This commit spools up a task on `Driver.Start()`, but is put to sleep for `Driver.ServerConnectTimeout`.

 - Public
 - Static
 - 30000ms by default 

After this amount of time, `Driver_StartupErrorEvent` fires, however... the task is cancelled, once we get the banner  from the server (which occurs after connecting).

Will be great if you can report back 👍

**Comment by spudwebb** [comment]
@marcus-j-davies 
I tested the latest v4 branch, and it works as expected,` StartUpError` fires after 30s. Thanks.

I wonder if we could do better and try to fire it as fast as possible when a connection error is detected by the Websocket.Client lib.
If I add the following lines to` InternalPrep()` `StartUpError `fires almost immediately if the server is not running. One drawback is that it fires every 2s, every time the websocket client tries reconnecting.

```csharp
            ClientWebSocket.DisconnectionHappened.Subscribe((DisconnectionInfo) =>
            {
                if (!Inited)
                {
                    StartUpError?.Invoke($"Could not connect to the server: {DisconnectionInfo?.Exception?.Message}");
                }
            });
```

What do you think?

**Comment by marcus-j-davies** [comment]
Hi @spudwebb 

I originally used `DisconnectionHappened` but fell victim to the same issue you faced with the reconnect cycle.
Problem we have here:

If self hosting, the socket server is not up until the native Driver its self is ready, its only at that point the Socket is ready for clients, the Server docs doesn't suggest allowing connections until then - as calls can be made to a non ready Driver:

https://github.com/zwave-js/ZWaveJS.NET/blob/a45a8347f280558de2a280c982f1d1163a62363b/PSI/server.js#L32

I set the reconnect to 2s to stop the client hanging around when the native Driver becomes ready
(1s just seemed greedy 😅)

Your proposal seems like it could work (checking the `inited` value), we could also trigger a different event if it was inited, as it's no longer a "Start Up Error" - but more an unexpected disconnect error now.

We could add
```csharp
public delegate void ConnectionLost(string Message);
public event ConnectionLost ConnectionLostEvent;
``` 

But also throttle the `StartUpError`, so only trigger every 10s.

so all-in


```csharp
ClientWebSocket.DisconnectionHappened.Subscribe((DisconnectionInfo) =>
{
   if (LastConnectionErrorEventTime > 10000)
    {
       if (!Inited)
       {
           StartUpError?.Invoke($"Could not connect to the server: {DisconnectionInfo?.Exception?.Message}");
       }
       else
       {
          ConnectionLost?.Invoke($"Connection to the server was lost: {DisconnectionInfo?.Exception?.Message}");
      }
  }
});
```

I think there is a compromise here, but not sure if there is a right answer?

Thoughts?

**Comment by spudwebb** [comment]
Hi @marcus-j-davies,
Looks good to me, but maybe make the 10s throttle configurable for those who want to get an error on first connection attempt.

**Comment by marcus-j-davies** [comment]
@spudwebb 

I have now implemented this routine.

If a connection error occurs (either trying to connect, or a dropped connection), it will trigger a reconnect (every 2s - as already does)

At the same time, either a `StartUpError` or `ConnectionLost` event is triggered (depends on `Inited`)

This will trigger again (based on the 2s reconnect) as long as its been > 10s since the last error event.
This can be set via a static property of `Driver.ServerErrorThrottleTime` (default is 10000ms)

see : https://github.com/zwave-js/ZWaveJS.NET/pull/31/commits/5dbb8693fcc3f158a8890ad6a97588e18c4629ac

**Comment by marcus-j-davies** [comment]
I'll close on the basis this has been addressed. Please re-open otherwise
