### ISSUE TITLE
Driver.Destroy() throws an exception if Driver.Controller is not initialized

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#39]
If Driver.Destroy() is called for a Driver instance that has not been successfully initialized for example, it throws an exception at 

`Controller.Nodes = null;`

because Controller is null. 
it is easily fixable by checking if Controller is null

    if (Controller != null)
    {
        Controller.Nodes = null;
        Controller = null;
    }

but I wonder what is the benefit of setting Controller.Nodes to null at all, since Controller itself is set to null on the next line?

**Comment by marcus-j-davies** [comment]
> but I wonder what is the benefit of setting Controller.Nodes to null at all,

Trust No One 😄 

Thanks! I'll fix it tonight!

**Comment by marcus-j-davies** [comment]
@spudwebb  - should be fixed
https://github.com/zwave-js/ZWaveJS.NET/pull/31/commits/41e87cf4be6a9b1edd79adb0f3887f81b7fda5b4

**Comment by spudwebb** [comment]
thanks!
