### ISSUE TITLE
Event handlers block processing of new events

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#46]
When the library calls an event handler, it blocks the processing of new events received from Z-Wave JS Server until the event handler returns.
So if what is implemented in the event handler is time consuming it can cause big delays in the whole application.
Moreover if the event handler itself synchronously calls another ZWave JS .NET method which expects a response from the Z-Wave JS server it creates a deadlock.

To workaround this issue all my event handlers look like this:
```c#
private void ExclusionStartedEventHandler()
  {
      //need a Task.Run here because event processing in ZWaveJS.NET is delayed by any event handler
      Task.Run(() =>
      {
....
      });
  }
```

I don't mind to keep doing this, but I wonder if there is any case where we actually want this blocking behavior?

**Comment by marcus-j-davies** [comment]
Nice catch!

Should be easy enough to move the trigger calls to a task! 
I'll review it this weekend, and will commit the changes to the branch I'm working on, that I mentioned in the controller node question.

**Comment by marcus-j-davies** [comment]
Fixed in recent commit
