### ISSUE TITLE
VirtualNode.GetDefinedValueIDs() throws a null reference exception (4.0.0 branch)

### ISSUE THREAD

**Issue by georgeinva2004** [zwave-js/ZWaveJS.NET#49]
Looks like there might be a small mistake in the path for the JO.SelectToken call in the following code:

```
Driver.Instance.Callbacks.Add(ID, (JO) =>
 {
     CMDResult Res = new CMDResult(JO);
     if (Res.Success)
     {
         Res.SetPayload(JO.SelectToken("result.valueIds").ToObject<ValueID[]>());
     }

     Result.SetResult(Res);
 });
```
The JSON in the response has "valueIDs" versus the "valueIds" being used in the path.

**Comment by marcus-j-davies** [comment]
Thanks @georgeinva2004 

Should be an easy fix.
I'll correct the path this weekend!

👍

**Comment by marcus-j-davies** [comment]
@georgeinva2004 
Should now be fixed.
